### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by olemis** [skycoin/homebrew-skycoin#1]
- [x] Remove `px4-sim` and related formulae
- [x] Update URLs for `gcc-arm-none-eabi*`
- [x] Update README
- [x] Add CX install formula (with license)
- [x] Fix Travis builds

**Comment by BigOokie** [comment]
The Readme.md needs to be updated as it refers to the wrong tap location

brew tap simelo/homebrew-skycoin

Should be:

brew tap skycoin/homebrew-skycoin

I note the Readme in the main CX project is correctly referring to this.

**Comment by olemis** [comment]
@BigOokie changed in #6 . Since all items look like finished and already in master , I'm closing this one. Feel free to reopen if you notice anything weird .
