### ISSUE TITLE
Update skycoin-cx formula for release v0.6.0

### ISSUE THREAD

**Issue by BigOokie** [skycoin/homebrew-skycoin#16]
## Expected Behavior
Formula for skycoin-cx to support latest release v0.6.0

## Actual Behavior
Currently supports v0.5.17

## Steps to Reproduce the Problem

  1. brew install skycoin-cx
  2. cx -v
  3. CX version 0.5.17

## Specifications

  - Version: v0.5.17
  - Platform: MacOS
  - Subsystem:

## Possible Solution
Formula file needs to be updated as follows:
- Update URL to https://github.com/skycoin/cx/releases/download/v0.6.0/cx-0.6.0-bin-macos-x64.zip
- Update SHA256 of the above file
- Update version to v0.6.0

**Comment by BigOokie** [comment]
Not "really" a bug, but was the classification it best fit into.
I will work on this now and raise a PR once its done. I cant assign this however.

**Comment by olemis** [comment]
@BigOokie could be a feature ...

**Comment by olemis** [comment]
@BigOokie cool ! request a review from me as soon as your PR is ready for merge

**Comment by BigOokie** [comment]
Yes -probably would have been better. Sorry

**Comment by olemis** [comment]
@BigOokie it's ok ... me just saying ...
